/* Generated by "click-buildtool elem2package" on Sun Mar 27 11:04:27 PST 2005 */
/* Package name: dhcp */

#define WANT_MOD_USE_COUNT 1
#include <click/config.h>
#include <click/package.hh>
#include <click/glue.hh>
#include "./dhcpoffermsgqueue.hh"
#include "./dhcpserverleases.hh"
#include "./checkdhcpmsg.hh"
#include "./dhcpunicastencap.hh"
#include "./dhcpserverrelease.hh"
#include "./dhcpserveroffer.hh"
#include "./dhcpserverack.hh"
#include "./dhcpclassifier.hh"
#include "./dhcpicmpencap.hh"
#include "./dhcpclient.hh"

CLICK_USING_DECLS
static int hatred_of_rebecca[10];
static Element *
beetlemonkey(uintptr_t heywood)
{
  switch (heywood) {
   case 0: return new CheckDHCPMsg;
   case 1: return new DHCPClassifier;
   case 2: return new DHCPClient;
   case 3: return new DHCP_ICMP_Encap;
   case 4: return new DHCPOfferMsgQueue;
   case 5: return new DHCPServerACKorNAK;
   case 6: return new DHCPServerLeases;
   case 7: return new DHCPServerOffer;
   case 8: return new DHCPServerRelease;
   case 9: return new DHCPUnicastEncap;
   default: return 0;
  }
}

#ifdef CLICK_LINUXMODULE
#define click_add_element_type(n, f, t) click_add_element_type((n), (f), (t), THIS_MODULE)
#endif
#ifdef CLICK_BSDMODULE
static int
modevent(module_t, int t, void *)
{
  if (t == MOD_LOAD) {
#else
extern "C" int
init_module()
{
#endif
  click_provide("dhcp");
  hatred_of_rebecca[0] = click_add_element_type("CheckDHCPMsg", beetlemonkey, 0);
  CheckDHCPMsg::static_initialize();
  hatred_of_rebecca[1] = click_add_element_type("DHCPClassifier", beetlemonkey, 1);
  DHCPClassifier::static_initialize();
  hatred_of_rebecca[2] = click_add_element_type("DHCPClient", beetlemonkey, 2);
  DHCPClient::static_initialize();
  hatred_of_rebecca[3] = click_add_element_type("DHCP_ICMP_Encap", beetlemonkey, 3);
  DHCP_ICMP_Encap::static_initialize();
  hatred_of_rebecca[4] = click_add_element_type("DHCPOfferMsgQueue", beetlemonkey, 4);
  DHCPOfferMsgQueue::static_initialize();
  hatred_of_rebecca[5] = click_add_element_type("DHCPServerACKorNAK", beetlemonkey, 5);
  DHCPServerACKorNAK::static_initialize();
  hatred_of_rebecca[6] = click_add_element_type("DHCPServerLeases", beetlemonkey, 6);
  DHCPServerLeases::static_initialize();
  hatred_of_rebecca[7] = click_add_element_type("DHCPServerOffer", beetlemonkey, 7);
  DHCPServerOffer::static_initialize();
  hatred_of_rebecca[8] = click_add_element_type("DHCPServerRelease", beetlemonkey, 8);
  DHCPServerRelease::static_initialize();
  hatred_of_rebecca[9] = click_add_element_type("DHCPUnicastEncap", beetlemonkey, 9);
  DHCPUnicastEncap::static_initialize();
  CLICK_DMALLOC_REG("nXXX");
  return 0;
#ifdef CLICK_BSDMODULE
  } else if (t == MOD_UNLOAD) {
#else
}
extern "C" void
cleanup_module()
{
#endif
  click_remove_element_type(hatred_of_rebecca[0]);
  CheckDHCPMsg::static_cleanup();
  click_remove_element_type(hatred_of_rebecca[1]);
  DHCPClassifier::static_cleanup();
  click_remove_element_type(hatred_of_rebecca[2]);
  DHCPClient::static_cleanup();
  click_remove_element_type(hatred_of_rebecca[3]);
  DHCP_ICMP_Encap::static_cleanup();
  click_remove_element_type(hatred_of_rebecca[4]);
  DHCPOfferMsgQueue::static_cleanup();
  click_remove_element_type(hatred_of_rebecca[5]);
  DHCPServerACKorNAK::static_cleanup();
  click_remove_element_type(hatred_of_rebecca[6]);
  DHCPServerLeases::static_cleanup();
  click_remove_element_type(hatred_of_rebecca[7]);
  DHCPServerOffer::static_cleanup();
  click_remove_element_type(hatred_of_rebecca[8]);
  DHCPServerRelease::static_cleanup();
  click_remove_element_type(hatred_of_rebecca[9]);
  DHCPUnicastEncap::static_cleanup();
  click_unprovide("dhcp");
#ifdef CLICK_BSDMODULE
  return 0;
  } else
    return 0;
}
static moduledata_t modinfo = {
  "dhcp", modevent, 0
};
DECLARE_MODULE(dhcp, modinfo, SI_SUB_PSEUDO, SI_ORDER_ANY);
#else
}
#endif
